name: sky_storage_hive
description: Local persistence implementation wrapping Hive and providing HiveDao.
version: 1.0.0
repository: https://github.com/Saurabh/sky_core
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '3.44.0'

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4

  sky_storage:
    path: ../sky_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints

