name: sky_utils
description: >
  Reusable, high-performance Dart and Flutter utility extensions and
  concurrency controls.
version: 1.0.1
repository: https://github.com/Saurrabhh/sky_core/tree/master/packages/sky_utils
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter

  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints
