name: sky_error
description: Result and Failure types for Sky Core.
version: 0.0.1
resolution: workspace

environment:
  sdk: '^3.11.5'
  flutter: '3.41.9'

dependencies:
  equatable: ^2.0.8
  fpdart: ^1.2.0
dev_dependencies:
  sky_lints:
    path: ../sky_lints
