name: sky_bloc
description: Standardized BLoC state management core for the Sky monorepo.
version: 2.0.5
repository: https://github.com/Saurrabhh/sky_core/tree/master/packages/sky_bloc
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  bloc: ^9.2.1
  bloc_lint: ^0.4.1

  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1

  sky_architecture: ^1.3.0
  sky_telemetry: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints
