name: sky_bloc
description: Standardized BLoC state management core for the Sky monorepo.
version: 1.1.2
repository: https://github.com/Saurrabhh/sky_core/tree/master/packages/sky_bloc
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  bloc: ^9.2.1

  flutter:
    sdk: flutter

  sky_architecture: ^1.0.2
  sky_telemetry: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints
