name: sky_bloc
description: Standardized BLoC state management core for the Sky monorepo.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '3.44.0'

dependencies:
  bloc: ^8.1.3

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  sky_architecture:
    path: ../sky_architecture

  sky_telemetry:
    path: ../sky_telemetry

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints
