name: sky_network
description: A robust, decoupled remote network client wrapped around Dio and Connectivity.
version: 1.1.7
repository: https://github.com/Saurrabhh/sky_core/tree/master/packages/sky_network
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  dio: ^5.4.3

  flutter:
    sdk: flutter

  fpdart: ^1.1.0

  http_certificate_pinning: ^3.0.1

  pretty_dio_logger: ^1.4.0

  sky_architecture: ^1.6.0
  sky_telemetry: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints
