name: sky_network
description: A robust, decoupled remote network client wrapped around Dio and Connectivity.
version: 1.0.0
repository: https://github.com/Saurabh/sky_core
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '3.44.0'

dependencies:
  dio: ^5.4.3

  flutter:
    sdk: flutter

  fpdart: ^1.1.0

  pretty_dio_logger: ^1.4.0

  sky_architecture:
    path: ../sky_architecture

  sky_telemetry:
    path: ../sky_telemetry

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints
