name: sky_di
description: Dependency injection setup for Sky Core.
version: 0.0.1
resolution: workspace

environment:
  sdk: '^3.11.5'
  flutter: '3.41.9'

dependencies:
  get_it: ^7.6.7
  injectable: ^2.3.2
dev_dependencies:
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  sky_lints:
    path: ../sky_lints
