name: sky_showcase
description: A Widgetbook-based showcase application for the Sky Design System.
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '3.44.0'

dependencies:
  flutter:
    sdk: flutter

  sky_design_system:
    path: ../../packages/sky_design_system

  widgetbook: ^3.23.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  build_runner: ^2.15.0

  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../../packages/sky_lints

  widgetbook_generator: ^3.23.0

flutter:
  uses-material-design: true
