name: sky_storage
description: Abstract storage interfaces for Sky Core.
publish_to: none
version: 0.0.1
resolution: workspace

environment:
  sdk: '^3.11.5'
  flutter: '3.41.9'

dependencies:
  sky_error:
    path: ../sky_error
dev_dependencies:
  sky_lints:
    path: ../sky_lints
