name: sky_design_system
description: Atomic design system for Sky Core applications.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '3.44.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints

flutter:
  uses-material-design: true
