name: sky_design_system
description: Atomic design system for Sky Core applications.
version: 1.2.1
repository: https://github.com/Saurrabhh/sky_core/tree/master/packages/sky_design_system
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  google_fonts: ^8.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  sky_lints:
    path: ../sky_lints

flutter:
  uses-material-design: true
