name: sky_media_kit
description: A robust media kit package providing wrappers for file selection, media picking, and local filesystem storage management.
version: 0.1.0
repository: https://github.com/Saurrabhh/sky_core/tree/master/packages/sky_media_kit
resolution: workspace

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  cross_file: ^0.3.5+2
  file_picker: ^12.1.1
  flutter:
    sdk: flutter
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  sky_architecture: ^1.7.2
