name: Deploy Widgetbook to GitHub Pages

on:
  workflow_dispatch:

# Grant permissions to write to the GitHub Pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.44.0
          cache: true

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: melos bs

      - name: Build Flutter Web
        run: melos exec --scope="sky_showcase" -- flutter build web --release --base-href "/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/sky_showcase/build/web
          branch: gh-pages